name: Build Brio

on:
  push:
    branches: '*'
    tags-ignore: '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Restore dependencies
      run: dotnet restore Brio.sln
      
    - name: Build Brio
      run: dotnet build --no-restore Brio.sln /p:Configuration=Release /p:DebugType=None /p:DebugSymbols=false /p:Version=${{ github.event.inputs.version }}

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        filename: '../../../../Brio.zip'
        directory: './Brio/bin/x64/Release/'
        exclusions: '*.pdb* *.xml*'

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: |
          ./Brio.zip
